// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.js",
  },
  datasource: {
    // Direct connection (port 5432) for migrations — bypasses PgBouncer pooler
    // which doesn't support advisory locks needed by Prisma Migrate.
    // Falls back to DATABASE_URL if DIRECT_DATABASE_URL isn't set.
    url: env("DIRECT_DATABASE_URL") ?? env("DATABASE_URL"),
  },
});
