#!/usr/bin/env node
/**
 * Generate app/theme.css from DESIGN.md.
 *
 * DESIGN.md is the canonical source of truth for design tokens. This script
 * emits a TWO-PART app/theme.css:
 *
 *   1. An `@theme` block — Tailwind v4's token registration. Every token here
 *      becomes BOTH a CSS custom property and a real utility class
 *      (--color-action → bg-action / text-action / border-action, etc.).
 *      This is the design system's front door: prefer these utilities over
 *      inline `var()` styles.
 *
 *   2. A `:root` legacy-alias block — the pre-@theme token names
 *      (--action, --bg-elevated, …) aliased onto the @theme properties, so
 *      the existing globals.css and inline styles keep working unchanged
 *      while call sites migrate. Scheduled for deletion in Phase 8 of
 *      docs/DS-PLAN.md.
 *
 * Data sources:
 *   - Colours: `npx design.md export --format tailwind` (resolves
 *     "{colors.x}" references and validates against the spec).
 *   - Shadows / motion / font family: parsed from the DESIGN.md frontmatter
 *     directly — the tailwind exporter drops these groups (verified
 *     2026-08-08, @google/design.md 0.1.1). Revisit if a newer version
 *     starts emitting them.
 *
 * Deliberately NOT emitted (each would silently restyle existing utilities —
 * see docs/DS-LOG.md Phase 2 for the counts; both await Caroline's decision):
 *   - the `rounded` scale (--radius-lg: 10px would shift 65 rounded-lg sites
 *     off Tailwind's 8px default)
 *   - a --text-* type scale (xs–lg already equal Tailwind's defaults; only
 *     xl 22px vs 20px diverges, 1 usage)
 *   - `spacing` (DESIGN.md documents Tailwind's default scale as in use)
 *
 * Run via: npm run build:ds  (predev/prebuild hooks keep it in sync)
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DESIGN_MD = resolve(ROOT, "DESIGN.md");
const OUT = resolve(ROOT, "app/theme.css");

function camelToKebab(s) {
  return s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function exportColors() {
  const json = execSync(`npx design.md export ${DESIGN_MD} --format tailwind`, {
    encoding: "utf8",
  });
  return JSON.parse(json).theme.extend.colors ?? {};
}

/**
 * Minimal frontmatter section reader for the groups the exporter drops.
 * Handles the flat `key: "value"  # comment` lines inside a named top-level
 * section. Not a YAML parser — just enough for DESIGN.md's shape.
 */
function readSection(name) {
  const src = readFileSync(DESIGN_MD, "utf8");
  const fm = src.split(/^---$/m)[1] ?? "";
  const lines = fm.split("\n");
  const start = lines.findIndex((l) => l.match(new RegExp(`^${name}:\\s*(#.*)?$`)));
  if (start === -1) return {};
  const out = {};
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^\S/.test(line)) break; // next top-level section
    const m = line.match(/^\s{2}(\w+):\s*("(.*?)"|[^#\n]*?)\s*(#.*)?$/);
    if (m) out[m[1]] = m[3] !== undefined ? m[3] : m[2].trim();
  }
  return out;
}

function buildCss(colors, fontSans, shadows, motion) {
  const lines = [
    "/* AUTOGENERATED from DESIGN.md by scripts/build-theme.mjs. Do not edit by hand. */",
    "/* To change tokens, edit DESIGN.md and run `npm run build:ds`. */",
    "",
    "/* Tailwind v4 token registration: every entry is a CSS variable AND a",
    " * utility class (bg-action, text-muted, shadow-floating, ...). */",
    "@theme {",
  ];

  for (const [name, value] of Object.entries(colors)) {
    lines.push(`  --color-${camelToKebab(name)}: ${value};`);
  }

  // Translucent overlays live in the custom `overlays:` frontmatter section
  // (the design.md spec rejects non-6-digit-hex colours).
  for (const [name, value] of Object.entries(readSection("overlays"))) {
    lines.push(`  --color-${camelToKebab(name)}: ${value};`);
  }

  if (fontSans) lines.push("", `  --font-sans: ${fontSans};`);
  if (shadows.floating) lines.push(`  --shadow-floating: ${shadows.floating};`);
  if (motion.ease) lines.push(`  --ease-standard: ${motion.ease};`);

  lines.push("}", "");

  lines.push(
    "/* Legacy aliases — the pre-@theme token names, kept so existing CSS and",
    " * inline var() styles work unchanged during the migration. New code should",
    " * use the utility classes (or --color-*). Deleted in DS-PLAN Phase 8. */",
    ":root {"
  );
  for (const name of Object.keys(colors)) {
    const kebab = camelToKebab(name);
    lines.push(`  --${kebab}: var(--color-${kebab});`);
  }
  if (motion.durationFast) lines.push(`  --duration-fast: ${motion.durationFast};`);
  if (motion.durationMedium) lines.push(`  --duration-medium: ${motion.durationMedium};`);
  lines.push("}", "");

  return lines.join("\n");
}

function main() {
  const colors = exportColors();
  const shadows = readSection("shadows");
  const motion = readSection("motion");
  const css = buildCss(colors, readFontSans(), shadows, motion);
  writeFileSync(OUT, css, "utf8");
  console.log(
    `✓ Wrote ${OUT} (${Object.keys(colors).length} colors via @theme + legacy aliases)`
  );
}

function readFontSans() {
  const src = readFileSync(DESIGN_MD, "utf8");
  const m = src.match(/^\s+sans:\s*"(.+?)"\s*$/m);
  return m ? m[1] : null;
}

main();
