#!/usr/bin/env node
/**
 * Generate app/theme.css from DESIGN.md.
 *
 * DESIGN.md is the canonical source of truth for design tokens. This script
 * reads it via the @google/design.md CLI's Tailwind export, then writes a
 * :root { --token-name: value; ... } block to app/theme.css which globals.css
 * imports. Component CSS in globals.css is unaffected.
 *
 * Run via: npm run build:ds
 *
 * Hooks: package.json's `predev` and `prebuild` invoke this so the CSS stays
 * in sync without anyone having to remember.
 *
 * camelCase → kebab-case mapping (matches existing globals.css convention):
 *   bgElevated → --bg-elevated
 *   actionHover → --action-hover
 *   buttonSecondaryBorder → --button-secondary-border
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DESIGN_MD = resolve(ROOT, "DESIGN.md");
const OUT = resolve(ROOT, "app/theme.css");

function camelToKebab(s) {
  return s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function exportTokens() {
  const json = execSync(`npx design.md export ${DESIGN_MD} --format tailwind`, {
    encoding: "utf8",
  });
  return JSON.parse(json).theme.extend;
}

function buildCss(tokens) {
  const lines = [
    "/* AUTOGENERATED from DESIGN.md by scripts/build-theme.js. Do not edit by hand. */",
    "/* To change tokens, edit DESIGN.md and run `npm run build:ds`. */",
    "",
    ":root {",
  ];

  // Colors
  if (tokens.colors) {
    for (const [name, value] of Object.entries(tokens.colors)) {
      lines.push(`  --${camelToKebab(name)}: ${value};`);
    }
  }

  lines.push("}", "");

  return lines.join("\n");
}

function main() {
  const tokens = exportTokens();
  const css = buildCss(tokens);
  writeFileSync(OUT, css, "utf8");
  console.log(`✓ Wrote ${OUT} (${Object.keys(tokens.colors ?? {}).length} colors)`);
}

main();
